---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: rhdh-realm
  namespace: demo-project
spec:
  keycloakCRName: demo-keycloak-instance
  realm:
    id: rhdh
    realm: rhdh
    displayName: "RHDH Realm"
    enabled: true
    browserFlow: browser
    identityProviders:
      - alias: github
        displayName: "GitHub"
        providerId: github
        enabled: true
        trustEmail: true
        storeToken: false
        addReadTokenRoleOnCreate: false
        authenticateByDefault: false
        linkOnly: false
        firstBrokerLoginFlowAlias: first broker login
        config:
          clientId: "clientid"
          clientSecret: "secret"
          defaultScope: "user:email"
    clients:
      - clientId: rhdh
        name: rhdh
        description: Red Hat Developer Hub Client
        enabled: true
        protocol: openid-connect
        publicClient: false
        redirectUris:
          - "https://rhdh.apps.cluster-xqcrg.dynamic.redhatworkshops.io/api/auth/*"
        rootUrl: "https://rhdh.apps.cluster-xqcrg.dynamic.redhatworkshops.io"
        adminUrl: "https://rhdh.apps.cluster-xqcrg.dynamic.redhatworkshops.io"
        baseUrl: "https://rhdh.apps.cluster-xqcrg.dynamic.redhatworkshops.io"
        webOrigins:
          - "+"
        secret: "developer-hub-secret"
        standardFlowEnabled: true
        implicitFlowEnabled: false
        directAccessGrantsEnabled: false
        serviceAccountsEnabled: false
        authorizationServicesEnabled: false
...
